server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
spring:
  mvc:
    view:
      prefix: /WEB-INF/blog/
      suffix: .jsp
  datasource:   
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springpjt
    username: springuser
    password:  
    
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate.format_sql: true